apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- backend-deployment.yaml
- frontend-service.yaml
- backend-service.yaml
images:
- name: nirmallyachakraborty/mini-gpt-frontend
  newTag: 8bc72b3
- name: nirmallyachakraborty/mini-gpt-backend
  newTag: 130b75c
