apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- backend-deployment.yaml
- frontend-service.yaml
- backend-service.yaml
images:
- name: nirmallyachakraborty/mini-gpt-frontend
  newTag: 660dd72
- name: nirmallyachakraborty/mini-gpt-backend
  newTag: 660dd72
